Error in gzfile(file, "rb") : cannot open the connection
